// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qjy59D0-uhRYSibbeJj65qbZzdU4bWM',
    appId: '1:665287090208:web:f89bcbb31d6ba3ee435c45',
    messagingSenderId: '665287090208',
    projectId: 'protofac-4093c',
    authDomain: 'protofac-4093c.firebaseapp.com',
    storageBucket: 'protofac-4093c.appspot.com',
    measurementId: 'G-1P50HR9THS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJ_745Qc4YjHfsegG9eW_1pc18TCWBgk',
    appId: '1:665287090208:android:858f4f728819f8ff435c45',
    messagingSenderId: '665287090208',
    projectId: 'protofac-4093c',
    storageBucket: 'protofac-4093c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshr-FC-DkjHoSfW7Q6km6waj3RrNW1_o',
    appId: '1:665287090208:ios:655abed2852f2a1c435c45',
    messagingSenderId: '665287090208',
    projectId: 'protofac-4093c',
    storageBucket: 'protofac-4093c.appspot.com',
    androidClientId: '665287090208-kq2r8ifcn1vnfvvod68u6m5497825ndl.apps.googleusercontent.com',
    iosClientId: '665287090208-vug1jouuod5togsccpff5anjobpq3b8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.protofacweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshr-FC-DkjHoSfW7Q6km6waj3RrNW1_o',
    appId: '1:665287090208:ios:6f821ec416267f8a435c45',
    messagingSenderId: '665287090208',
    projectId: 'protofac-4093c',
    storageBucket: 'protofac-4093c.appspot.com',
    androidClientId: '665287090208-kq2r8ifcn1vnfvvod68u6m5497825ndl.apps.googleusercontent.com',
    iosClientId: '665287090208-vfmrjao6b37g0s8lqa1k35rfdq6guaus.apps.googleusercontent.com',
    iosBundleId: 'com.example.protofacweb.RunnerTests',
  );
}
