version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
