// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSHZkLmB6xhli_-DI1UgRmV2D8903exh8',
    appId: '1:198462244740:web:64a8b8eefd08018ccfbfd1',
    messagingSenderId: '198462244740',
    projectId: 'protofac-61bc1',
    authDomain: 'protofac-61bc1.firebaseapp.com',
    storageBucket: 'protofac-61bc1.appspot.com',
    measurementId: 'G-ZCGE1NQR73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX11kXntk_g81B7zFpO9OD35p6xCcPRvY',
    appId: '1:198462244740:android:51f10c9e9dda36eccfbfd1',
    messagingSenderId: '198462244740',
    projectId: 'protofac-61bc1',
    storageBucket: 'protofac-61bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKzP79Qym4uCOrKgoMT3ivKyupDvhOYw',
    appId: '1:198462244740:ios:e8df95abdccb3e83cfbfd1',
    messagingSenderId: '198462244740',
    projectId: 'protofac-61bc1',
    storageBucket: 'protofac-61bc1.appspot.com',
    iosClientId: '198462244740-d81i1e87k0v6ofopgfk2sdkk8nup1abs.apps.googleusercontent.com',
    iosBundleId: 'com.example.protofac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKzP79Qym4uCOrKgoMT3ivKyupDvhOYw',
    appId: '1:198462244740:ios:e8df95abdccb3e83cfbfd1',
    messagingSenderId: '198462244740',
    projectId: 'protofac-61bc1',
    storageBucket: 'protofac-61bc1.appspot.com',
    iosClientId: '198462244740-d81i1e87k0v6ofopgfk2sdkk8nup1abs.apps.googleusercontent.com',
    iosBundleId: 'com.example.protofac',
  );
}
